LightNovelSystem/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.views.static import serve
from django.conf import settings
from app01.views import account, publisher, author, lightnovel, illustrator

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),

    # 登录
    path('', account.login),
    path('login/', account.login),
    path('regist/', account.regist),
    path('image/code/', account.image_code),
    path('logout/', account.logout),

    # 出版社
    path('publisher/list/', publisher.publisher_list),
    path('publisher/add/', publisher.publisher_add),
    path('publisher/<int:nid>/edit/', publisher.publisher_edit),
    path('publisher/delete/', publisher.publisher_delete),

    #作者
    path('author/list/', author.author_list),
    path('author/add/', author.author_add),
    path('author/delete/', author.author_delete),
    path('author/detail/', author.author_detail),
    path('author/edit/', author.author_edit),

    # 插画师
    path('illustrator/list/', illustrator.illustrator_list),
    path('illustrator/add/', illustrator.illustrator_add),
    path('illustrator/delete/', illustrator.illustrator_delete),
    path('illustrator/detail/', illustrator.illustrator_detail),
    path('illustrator/edit/', illustrator.illustrator_edit),

    # 轻小说
    path('lightnovel/list/', lightnovel.lightnovel_list),
    path('lightnovel/add/', lightnovel.lightnovel_add),
    path('lightnovel/<int:nid>/delete/', lightnovel.lightnovel_delete),
    path('lightnovel/<int:nid>/detail/', lightnovel.lightnovel_detail),
    path('lightnovel/<int:nid>/edit/', lightnovel.lightnovel_edit),
]

app01/models.py
from django.db import models


# Create your models here.

# 用户类
class Admin(models.Model):
    username = models.CharField(verbose_name='用户名', max_length=32, unique=True, null=False)
    password = models.CharField(verbose_name='密码', max_length=64, null=False)

    def __str__(self):
        return self.username

# 出版社类
class Publisher(models.Model):
    publisher_id = models.AutoField(verbose_name='ID', primary_key=True)
    name = models.CharField(verbose_name='名称', max_length=64, null=False, unique=True)
    date = models.DateField(verbose_name='创立日期', max_length=64, blank=True, null=True)
    introduction = models.TextField(verbose_name='简介', blank=True, null=True)

    def __str__(self):
        return self.name


# 作者类
class Author(models.Model):
    author_id = models.AutoField(verbose_name='ID', primary_key=True)
    name = models.CharField(verbose_name='姓名', max_length=64, null=False, unique=True)
    gender_choices = (
        (1, '男'),
        (2, '女')
    )
    gender = models.SmallIntegerField(verbose_name='性别', choices=gender_choices, null=False)
    date = models.DateField(verbose_name='出生时间', max_length=64, blank=True, null=True)
    email = models.EmailField(verbose_name='邮箱', max_length=64, null=True, blank=True)

    def __str__(self):
        return self.name

# 插画师类
class Illustrator(models.Model):
    illustrator_id = models.AutoField(verbose_name='ID', primary_key=True)
    name = models.CharField(verbose_name='姓名', max_length=64, null=False, unique=True)
    gender_choices = (
        (1, '男'),
        (2, '女')
    )
    gender = models.SmallIntegerField(verbose_name='性别', choices=gender_choices, null=False)
    date = models.DateField(verbose_name='出生时间', max_length=64, blank=True, null=True)
    email = models.EmailField(verbose_name='邮箱', max_length=64, null=True, blank=True)

    def __str__(self):
        return self.name

# 轻小说类型类：
class Type(models.Model):
    type_id = models.AutoField(verbose_name='ID', primary_key=True)
    type = models.CharField(verbose_name='类型', max_length=64, null=False, unique=True)

    def __str__(self):
        return self.type

# 轻小说类
class LightNovel(models.Model):
    book_id = models.AutoField(verbose_name='ID', primary_key=True)
    name = models.CharField(verbose_name='名称', max_length=64, null=False, unique=True)
    author = models.ForeignKey(verbose_name='作者', to=Author, to_field='author_id', on_delete=models.CASCADE, null=True)
    illustrator = models.ForeignKey(verbose_name='插画师', to=Illustrator, to_field='illustrator_id', on_delete=models.CASCADE, null=True)
    publisher = models.ForeignKey(verbose_name='出版社', to=Publisher, to_field='publisher_id', on_delete=models.CASCADE, null=True)
    # type置空，其他级联删除
    type = models.ForeignKey(verbose_name='类型', to=Type, to_field='type_id', null=True, blank=True, on_delete=models.SET_NULL)
    count = models.CharField(verbose_name='卷数', max_length=64, null=True, blank=True)
    update_choices = (
        (1, "完结"),
        (0, "未完结")
    )
    update = models.SmallIntegerField(verbose_name='是否更新完', choices=update_choices, null=True, blank=True)
    date = models.DateField(verbose_name='出版日期', max_length=64, blank=True, null=True)
    introduction = models.TextField(verbose_name='简介', null=True, blank=True)
    image = models.FileField(verbose_name='封面', upload_to='image', default='image/default.png')

app01/views/account.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time : 2023/12/16 13:14
# @Author : natsume
# @File : account.py
# @Software: PyCharm

from io import BytesIO

from django import forms
from django.http import HttpResponse
from django.shortcuts import render, redirect

from app01 import models
from app01.utils.bootstrap import BootStrapForm, BootStrapModelForm
from app01.utils.code import check_code
from app01.utils.encrypt import md5

class LoginForm(BootStrapForm):
    username = forms.CharField(
        label="用户名",
        widget=forms.TextInput(attrs={"class": "form-control"}),
        required=True
    )
    password = forms.CharField(
        label="密码",
        widget=forms.PasswordInput(attrs={"class": "form-control"}, render_value=True),
        required=True
    )
    def clean_password(self):
        pwd = self.cleaned_data.get('password')
        return md5(pwd)

def login(request):
    if request.method == 'GET':
        form = LoginForm()
        return render(request, 'login.html', {'form': form})
    form = LoginForm(data=request.POST)
    print(request)
    if form.is_valid():
        admin_object = models.Admin.objects.filter(**form.cleaned_data).first()
        if not admin_object:
            form.add_error("password", "用户名或密码错误")
            return render(request, 'login.html', {'form': form})

        request.session["info"] = {'name': admin_object.username}
        request.session.set_expiry(60 * 60 * 24 * 7)
        return redirect('/lightnovel/list/')
    return render(request, 'login.html', {'form': form})

class RegistForm(BootStrapModelForm):
    username = forms.CharField(
        label="用户名",
        widget=forms.TextInput(attrs={"class": "form-control"}),
        required=True
    )
    password = forms.CharField(
        label="密码",
        widget=forms.PasswordInput(attrs={"class": "form-control"}, render_value=True),
        required=True
    )
    code = forms.CharField(
        label="验证码",
        widget=forms.TextInput,
        required=True
    )
    def clean_password(self):
        pwd = self.cleaned_data.get('password')
        return md5(pwd)
    class Meta:
        model = models.Admin
        fields = ["username", "password"]

def regist(request):
    if request.method == 'GET':
        form = RegistForm()
        return render(request, 'regist.html', {'form': form})
    form = RegistForm(data=request.POST)
    if form.is_valid():
        user_input_code = form.cleaned_data.pop('code')
        code = request.session.get('image_code', "")
        if code.upper() != user_input_code.upper():
            form.add_error('code', "验证码错误")
            return render(request, 'regist.html', {'form': form})

        # print(form.cleaned_data)
        form.save()
        return redirect('/login/')
    return render(request, 'regist.html', {'form': form})

def image_code(request):
    img, code_string = check_code()
    # print(code_string)

    # 写入到自己的session中
    request.session['image_code'] = code_string
    # 设置60s超时
    request.session.set_expiry(60)

    stream = BytesIO()
    img.save(stream, 'png')
    return HttpResponse(stream.getvalue())

def logout(request):
    request.session.clear()
    return redirect('/login/')

app01/views/author.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time : 2023/12/16 14:44
# @Author : natsume
# @File : author.py
# @Software: PyCharm
from django.shortcuts import render, redirect
from django import forms
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, JsonResponse

from app01 import models
from app01.utils.bootstrap import BootStrapModelForm
from app01.utils.pagination import Pagination

class AuthorModelForm(BootStrapModelForm):
    class Meta:
        model = models.Author
        exclude = ['author_id']

def author_list(request):
    form = AuthorModelForm()
    data_dict = {}
    search_data = request.GET.get("q", "")
    if search_data:
        data_dict["name__contains"] = search_data
    queryset = models.Author.objects.filter(**data_dict)
    page_object = Pagination(request, queryset, page_size=10)
    context = {
        'form': form,
        'queryset': page_object.page_queryset,
        'page_string': page_object.html(),
        'search_data': search_data
    }
    return render(request, 'author_list.html', context)

# 添加作者
@csrf_exempt
def author_add(request):
    form = AuthorModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return JsonResponse({"status": True})
    return JsonResponse({"status": False, "error": form.errors})

# 删除作者
def author_delete(request):
    uid = request.GET.get("uid")
    exists = models.Author.objects.filter(author_id=uid).exists()
    if not exists:
        return JsonResponse({"status": False, 'error': "数据不存在"})
    models.Author.objects.filter(author_id=uid).delete()
    return JsonResponse({"status": True})

# 点击修改查询该作者的信息
def author_detail(request):
    uid = request.GET.get("uid")
    row_dict = models.Author.objects.filter(author_id=uid).values("name", "gender", "date", "email").first()
    if not row_dict:
        return JsonResponse({"status": False, "error": "数据不存在"})
    result = {
        "status": True,
        "data": row_dict
    }
    return JsonResponse(result)

@csrf_exempt
def author_edit(request):
    uid = request.GET.get("uid")
    row_object = models.Author.objects.filter(author_id=uid).first()
    if not row_object:
        return JsonResponse({"status": False, "tips": "数据不存在"})
    form = AuthorModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return JsonResponse({"status": True})
    return JsonResponse({"status": False, "error": form.errors})

app01/views/illustrator.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time : 2023/12/16 14:45
# @Author : natsume
# @File : illustrator.py
# @Software: PyCharm
from django.shortcuts import render, redirect
from django import forms
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, JsonResponse

from app01 import models
from app01.utils.bootstrap import BootStrapModelForm
from app01.utils.pagination import Pagination

class IllustratorModelForm(BootStrapModelForm):
    class Meta:
        model = models.Illustrator
        exclude = ['illustrator_id']

# 插画师列表
def illustrator_list(request):
    form = IllustratorModelForm()
    data_dict = {}
    search_data = request.GET.get("q", "")
    if search_data:
        data_dict["name__contains"] = search_data
    queryset = models.Illustrator.objects.filter(**data_dict)
    page_object = Pagination(request, queryset, page_size=10)
    context = {
        'form': form,
        'queryset': page_object.page_queryset,
        'page_string': page_object.html(),
        'search_data': search_data
    }
    return render(request, 'illustrator_list.html', context)

# 添加插画师
@csrf_exempt
def illustrator_add(request):
    form = IllustratorModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return JsonResponse({"status": True})
    return JsonResponse({"status": False, "error": form.errors})

# 删除插画师
def illustrator_delete(request):
    uid = request.GET.get("uid")
    exists = models.Illustrator.objects.filter(illustrator_id=uid).exists()
    if not exists:
        return JsonResponse({"status": False, 'error': "数据不存在"})
    models.Illustrator.objects.filter(illustrator_id=uid).delete()
    return JsonResponse({"status": True})

# 点击修改查询该插画师的信息
def illustrator_detail(request):
    uid = request.GET.get("uid")
    row_dict = models.Illustrator.objects.filter(illustrator_id=uid).values("name", "gender", "date", "email").first()
    if not row_dict:
        return JsonResponse({"status": False, "error": "数据不存在"})
    result = {
        "status": True,
        "data": row_dict
    }
    return JsonResponse(result)

@csrf_exempt
def illustrator_edit(request):
    uid = request.GET.get("uid")
    row_object = models.Illustrator.objects.filter(illustrator_id=uid).first()
    if not row_object:
        return JsonResponse({"status": False, "tips": "数据不存在"})
    form = IllustratorModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return JsonResponse({"status": True})
    return JsonResponse({"status": False, "error": form.errors})

app01/views/lightnovel.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time : 2023/12/16 14:45
# @Author : natsume
# @File : lightnovel.py
# @Software: PyCharm
from django.shortcuts import render, redirect
from django import forms

from app01 import models
from app01.utils.bootstrap import BootStrapModelForm
from app01.utils.pagination import Pagination

class LightNovelModelForm(BootStrapModelForm):
    bootstrap_exclude_fields = ['book_id', 'image']
    class Meta:
        model = models.LightNovel
        fields = "__all__"

def lightnovel_list(request):
    data_dict = {}
    search_data = request.GET.get("q", "")
    if search_data:
        data_dict["name__contains"] = search_data
    queryset = models.LightNovel.objects.filter(**data_dict)
    page_object = Pagination(request, queryset, page_size=10)
    context = {
        'queryset': page_object.page_queryset,
        'page_string': page_object.html(),
        'search_data': search_data
    }
    return render(request, 'lightnovel_list.html', context)

def lightnovel_add(request):
    title = "添加小说"
    if request.method == "GET":
        form = LightNovelModelForm()
        return render(request, 'lightnovel_add.html', {'form': form, 'title': title})
    form = LightNovelModelForm(data=request.POST, files=request.FILES)
    if(form.is_valid()):
        form.save()
        return redirect("/lightnovel/list/")
    return render(request, 'lightnovel_add.html', {'form': form, 'title': title})

def lightnovel_detail(request, nid):
    obj = models.LightNovel.objects.filter(book_id=nid).first()
    return render(request, 'lightnovel_detail.html', {'obj': obj})

def lightnovel_edit(request, nid):
    title = "修改小说"
    if request.method == "GET":
        row_object = models.LightNovel.objects.filter(book_id=nid).first()
        form = LightNovelModelForm(instance=row_object)
        return render(request, 'lightnovel_edit.html', {'form': form, 'title': title, 'img': row_object.image})
    row_object = models.LightNovel.objects.filter(book_id=nid).first()
    form = LightNovelModelForm(data=request.POST, files=request.FILES, instance=row_object)
    if(form.is_valid()):
        form.save()
        return redirect('/lightnovel/list/')
    return render(request, 'lightnovel_edit.html', {'form': form, 'title': title})

def lightnovel_delete(request, nid):
    models.LightNovel.objects.filter(book_id=nid).delete()
    return redirect('/lightnovel/list/')

app01/templates/author.html
{% extends 'layout.html' %}

{% block navli %}
    <li class="nav-item"><a class="nav-link" href="/lightnovel/list/">小说管理</a></li>
  <li class="nav-item active"><a class="nav-link" href="/author/list/">作者管理</a></li>
  <li class="nav-item"><a class="nav-link" href="/illustrator/list/">插画师管理</a></li>
  <li class="nav-item"><a class="nav-link" href="/publisher/list/">出版社管理</a></li>
{% endblock %}

app01/templates/author_list.html
{% extends 'author.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div style="margin-bottom: 20px;" class="clearfix">
            <nav class="navbar">
                <input type="submit" value="添加作者" class="btn btn-primary" id="btnAdd" data-toggle="modal" data-target="#myModal" />
              <form class="form-inline" method="get">
                <input class="form-control mr-sm-2" type="search" placeholder="关键字" aria-label="Search" name="q" value="{{ search_data }}">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
              </form>
            </nav>
        </div>
        <div class="card" >
          <div class="card-header">作者列表</div>
          <div class="card-body" style="padding: 0px;">
            <table class="table table-striped" style="margin-bottom: 0px;">
              <thead>
                <tr>
                  <th scope="col" style="text-align: center;">ID</th>
                  <th scope="col" style="text-align: center;">姓名</th>
                  <th scope="col" style="text-align: center;">性别</th>
                  <th scope="col" style="text-align: center;">出生时间</th>
                  <th scope="col" style="text-align: center;">邮箱</th>
                  <th scope="col" style="text-align: center;">操作</th>
                </tr>
              </thead>
              <tbody>
              {% for obj in queryset %}
                <tr>
                  <th scope="row" style="text-align: center; " >{{ obj.author_id }}</th>
                  <td style="text-align: center; ">{{ obj.name }}</td>
                  <td style="text-align: center; ">{{ obj.get_gender_display }}</td>
                  <td style="text-align: center;">{{ obj.date }}</td>
                  <td style="text-align: center;">{{ obj.email }}</td>
                  <td style="text-align: center;">
                      <input uid="{{ obj.author_id }}" type="button" class="btn btn-primary btn-sm btn-edit" value="编辑"/>
                      <input uid="{{ obj.author_id }}" type="button" class="btn btn-danger btn-sm btn-delete" value="删除" />
{#                      <a class="btn btn-primary btn-sm" href="/author/{{ obj.author_id }}/edit/">编辑</a>#}
{#                      <a class="btn btn-danger btn-sm" href="/author/delete/?nid={{ obj.author_id }}">删除</a>#}
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
        <nav aria-label="Page navigation example" style="margin-top: 40px;">
            <ul class="pagination">
                {{ page_string }}
            </ul>
        </nav>
    </div>

    {#    添加/编辑 订单模态框  #}
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                  <h6 class="modal-title" id="myModalLabel"></h6>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              </div>
              <div class="modal-body">
                <form id="formAdd">
                        <div class="clearfix">
                            {% for field in form %}
                                <div class="col-xs-6">
                                    <div class="form-group" style="position: relative;margin-bottom: 20px;">
                                        <label>{{ field.label }}</label>
                                        {{ field }}
                                        <span class="error-msg" style="color: red;position: absolute;"></span>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>

                    </form>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                <button id="btnSave" type="button" class="btn btn-primary">保存</button>
              </div>
            </div>
          </div>
      </div>

    {#    删除订单模态框#}
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" >
  <div class="modal-dialog" role="document">
      <div class="modal-content">
          <div class="modal-header">
              <h4 class="modal-title" style="color: red;">删除</h4>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          </div>
          <div class="modal-body">
            <p style="margin: 10px 0;">删除后，所有关联的相关数据都会被删除。</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-danger" id="btnConfirmDelete">确定</button>
        <button type="button" class="btn btn-default" id="btnCancel">取消</button>
          </div>
        </div>
{#    <div class="alert alert-danger alert-dismissible fade in" role="alert">#}
{#      <h4>是否确定删除？</h4>#}
{#      <p style="margin: 10px 0;">删除后，所有关联的相关数据都会被删除。</p>#}
{#      <p style="text-align: right;">#}
{##}
{#      </p>#}
{#    </div>#}
  </div>
</div>
{% endblock %}

{% block js %}
    <script src="{% static 'plugins/bootstrap-datepicker/js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js' %}"></script>
    <script type="text/javascript">
        var DELETE_ID;
        var EDIT_ID;
        $(function(){
            bindBtnAddEvent();

            bindBtnSaveEvent();

            bindBtnDeleteEvent();
            bindBtnConfirmDeleteEvent();
            bindBtnCancelEvent();

            bindBtnEditEvent();
        })

        function bindBtnAddEvent(){
            $("#btnAdd").click(function (){
                EDIT_ID = undefined;
                $("#formAdd")[0].reset();
                $("#myModalLabel").text("新建");
                $('#myModal').modal('show');
            })
        }

        function bindBtnSaveEvent(){
            $("#btnSave").click(function (){

                $(".error-msg").empty();

                if(EDIT_ID){
                    doEdit();
                }else{
                    doAdd();
                }

            })
        }

        function doEdit(){
            $.ajax({
                    url: '/author/edit/?uid=' + EDIT_ID,
                    type: 'post',
                    data: $("#formAdd").serialize(),
                    dataType: "json",
                    success: function(res){
                        if(res.status){
                            {#alert("创建成功");#}
                            $("#formAdd")[0].reset();
                            $('#myModal').modal('hide');
                            location.reload();
                        }else{
                            if(res.tips){
                                alert(res.tips);
                            }else{
                                $.each(res.error, function(name, errorList){
                                    $("#id_" + name).next().text(errorList[0])
                                })
                            }
                        }
                    }
                })
        }

        function doAdd(){
            $.ajax({
                    url: '/author/add/',
                    type: 'post',
                    data: $("#formAdd").serialize(),
                    dataType: "json",
                    success: function(res){
                        if(res.status){
                            {#alert("创建成功");#}
                            $("#formAdd")[0].reset();
                            $('#myModal').modal('hide');
                            location.reload();
                        }else{
                            $.each(res.error, function(name, errorList){
                                $("#id_" + name).next().text(errorList[0])
                            })
                        }
                    }
                })
        }

        function bindBtnDeleteEvent(){
            $(".btn-delete").click(function () {
                {#alert("点击了删除");#}
                $("#deleteModal").modal("show");

                DELETE_ID = $(this).attr("uid");
            })
        }

        function bindBtnConfirmDeleteEvent(){
            $("#btnConfirmDelete").click(function(){
                $.ajax({
                    url: "/author/delete/",
                    type: "GET",
                    data:{
                        uid: DELETE_ID
                    },
                    dataType: "JSON",
                    success: function(res){
                        if(res.status){
                            $("#deleteModal").modal("hide");
                            DELETE_ID = 0;
                            location.reload();
                        }else{
                            alert("删除失败");
                        }
                    }
                })
            })
        }

        function bindBtnCancelEvent(){
            $("#btnCancel").click(function (){
                $("#deleteModal").modal("hide");
            })
        }

        function bindBtnEditEvent(){
            $(".btn-edit").click(function (){
                var uid = $(this).attr("uid");
                $("#formAdd")[0].reset();
                {#$("#myModalLabel").text("编辑")#}
                {#$("#myModal").modal('show');#}
                EDIT_ID = uid;
                $.ajax({
                    url: "/author/detail/",
                    type: "GET",
                    data: {
                        uid: uid
                    },
                    dataType: "JSON",
                    success: function (res){
                        if(res.status){
                            console.log(res);
                            $("#myModalLabel").text("编辑");
                            $("#myModal").modal("show");
                            $.each(res.data, function(name, value){
                                $("#id_" + name).val(value);
                            })
                        }else{
                            alert(res.error);
                        }
                    }
                })
            })
        }
    </script>
    <script>
        $(function(){
            $("#id_date").datepicker({
                format: 'yyyy-mm-dd',
                startDate: '1900-01-01',
                language: "zh-CN",
                autoclose: true
            });
        })


    </script>
{% endblock %}

app01/templates/lightnovel_detail.html
{% extends 'lightnovel.html' %}
{% load static %}

{% block content %}
    <div class="container" style="margin-top: 30px;">
        <div style="background-color: white; padding: 30px; height: 600px;">
            <div style="margin-bottom: 30px;">
                <a href="javascript:history.back(-1)" class="btn btn-success">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-return-left" viewBox="0 0 16 16">
                  <path fill-rule="evenodd" d="M14.5 1.5a.5.5 0 0 1 .5.5v4.8a2.5 2.5 0 0 1-2.5 2.5H2.707l3.347 3.346a.5.5 0 0 1-.708.708l-4.2-4.2a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 8.3H12.5A1.5 1.5 0 0 0 14 6.8V2a.5.5 0 0 1 .5-.5z"/>
                </svg> 返 回</a>
            </div>
            <span style=" float: left">
                <img style="width: 300px; margin-right: 20px; " src="/media/{{ obj.image }}" class="rounded float-left" alt="...">
            </span>
            <span>
                <h2 style="font-family: 楷体; font-weight: bold;">{{ obj.name }}</h2>
                <div style="font-family: 楷体; font-weight: bold; font-size: 20px;">{{ obj.author }} 著</div>
                <div style="font-family: 楷体; font-weight: bold; font-size: 20px;">{{ obj.illustrator }} 画</div>
                <div style="font-family: 楷体; font-weight: bold; font-size: 20px;">{{ obj.publisher }} 出版社</div>
                <div style="font-family: 楷体; font-weight: bold; font-size: 20px;">{{ obj.count }} 卷</div>
                <div style="font-family: 楷体; font-weight: bold; font-size: 20px;">{{ obj.get_update_display }} </div>
                <div style="font-family: 楷体; font-weight: bold; font-size: 20px;">出版日期：{{ obj.date }}</div>
                <p style=>{{ obj.introduction }}</p>
                <div>
                    <a href="/lightnovel/{{ obj.book_id }}/edit/" type="button" class="btn btn-primary btn-xs btn-edit" value="编辑">修改</a>
                    <a href="/lightnovel/{{ obj.book_id }}/delete/" type="button" class="btn btn-primary btn-xw btn-danger" value="删除">删除</a>
                </div>
            </span>
        </div>
    </div>
{% endblock %}

app01/templates/lightnovel_edit.html
{% extends 'lightnovel.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="card">
          <div class="card-header">
              {{ title }}
          </div>
          <div class="card-body">
            <form method="post" novalidate enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                  <div class="form-group">
                    <label style="font-weight: bold;">{{ field.label }}</label>
                      {{ field }}
                      <span style="color: red">{{ field.errors.0 }}</span>
                  </div>
                {% endfor %}
              <button type="submit" class="btn btn-primary">修 改</button>
              <a href="javascript:history.back(-1)" class="btn btn-dark">取消</a>
            </form>
          </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static 'plugins/bootstrap-datepicker/js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js' %}"></script>
    <script>
        $(function(){
            $("#id_date").datepicker({
                format: 'yyyy-mm-dd',
                startDate: '1900-01-01',
                language: "zh-CN",
                autoclose: true
            });
        })
    </script>
{% endblock %}